FROM leeonky/c-dev:ubuntu

RUN sudo apt-get update && sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev portaudio19-dev libass-dev

RUN sudo apt-get install -y \
	libavcodec-dev \
	libavformat-dev \
	libavutil-dev \
	libswresample-dev \
	libswscale-dev

CMD bash
